version: '3'
services:
  # TODO: work in progress
  event-api:
    image: bellcd/drjohnson_event-service
    build: .
    ports:
      # TODO: read from .env
      - '80:80'
    depends_on:
      - redis
    env_file: .env
    command: "npm start"
    restart: "no"
    deploy:
      mode: replicated
      replicas: 3
  redis:
    image: redis
    ulimits:
      nofile:
        soft: 15000
        hard: 15000
    # restart: always