version: '3'
services:
  # TODO: work in progress
  event-api:
    image: bellcd/drjohnson_event-api:1
    ports:
      # TODO: read from .env
      - '80:80'
    depends_on:
      - redis
    env_file: .env
    command: "npm start"
    restart: "no"
  redis:
    image: redis:alpine
    # restart: always